services:
  mosquitto:
    container_name: mqtt-relay
    build: mosquitto
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
