name: PlatformIO CI
on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: mk4-release
            ud_gen: MK4
            ud_debug: 0
          - environment: mk5-release
            ud_gen: MK5
            ud_debug: 0
          - environment: mk6-release
            ud_gen: MK6
            ud_debug: 0
          - environment: mk7-release
            ud_gen: MK7
            ud_debug: 0
          - environment: mk7-debug
            ud_gen: MK7
            ud_debug: 1
          # TODO Re-add native
          # - environment: native

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.8
          command: UD_GEN=${{ matrix.ud_gen }} UD_DEBUG=${{ matrix.ud_debug }} ./idfx.py build

      - name: Rename firmware artifact
        if: matrix.environment != 'native'
        run: cp ${{ github.workspace }}/build/${{ matrix.ud_gen }}/ugly-duckling.bin ugly-duckling-${{ matrix.environment }}.bin

      - name: Upload firmware artifact
        if: matrix.environment != 'native'
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: ugly-duckling-${{ matrix.environment }}.bin
          if-no-files-found: error

      # TODO Re-add unit tests
      # - name: Run unit tests
      #   if: matrix.environment == 'native'
      #   run: pio test --environment native

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: firmware-*/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
