name: CI Build
on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: mk4-release
            ud_gen: MK4
            ud_debug: 0
            target: esp32s2
          - environment: mk5-release
            ud_gen: MK5
            ud_debug: 0
            target: esp32s3
          - environment: mk6-release
            ud_gen: MK6
            ud_debug: 0
            target: esp32s3
          - environment: mk7-release
            ud_gen: MK7
            ud_debug: 0
            target: esp32s3
          - environment: mk7-debug
            ud_gen: MK7
            ud_debug: 1
            target: esp32s3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.2
          target: ${{ matrix.target }}
          command: idf.py build -DUD_GEN=${{ matrix.ud_gen }} -DUD_DEBUG=${{ matrix.ud_debug }}

      - name: Rename firmware artifact
        run: cp ${{ github.workspace }}/build/ugly-duckling.bin ugly-duckling-${{ matrix.environment }}.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: ugly-duckling-${{ matrix.environment }}.bin
          if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: firmware-*/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
